### ISSUE TITLE
What's the licence of this project?

### ISSUE THREAD

**Issue by blaisewf** [thepowerfuldeez/rvc-trainer#1]
Hi, I have found some very interesting features in this project, and I would like to know if this code is licensed to be implemented in others.

Thanks!

**Comment by thepowerfuldeez** [comment]
Hi @blaise-tk ! Absolutely, you can use code in this repo in your work, by citing me

**Comment by blaisewf** [comment]
> Hi @blaise-tk ! Absolutely, you can use code in this repo in your work, by citing me

I will make sure to do so if I can finally take advantage of it, was the improvement by replacing HIFIGAN very noticeable?

**Comment by thepowerfuldeez** [comment]
@blaise-tk to be honest, since BigGAN training is longer and more unstable, I couldn't get it converged on my gpu-poor setup :)
code is adaptation of original implementation by nvidia + nsf filtering from original rvc

**Comment by blaisewf** [comment]
> @blaise-tk to be honest, since BigGAN training is longer and more unstable, I couldn't get it converged on my gpu-poor setup :) code is adaptation of original implementation by nvidia + nsf filtering from original rvc

I was able to train a model successfully but when doing inference I got this error and the audio was not generated 

"expected mat1 and mat2 to have the same dtype, but got: float != struct c10::Half"

Using a 3060ti with fp16

https://github.com/IAHispano/Applio/commits/exp-bigvgan/ I implemented it here if you want to try it, it has a graphical interface

**Comment by blaise-tk** [comment]
https://github.com/IAHispano/Applio/commits/exp-bigvgan/ I implemented it here if you want to try it, it has a graphical interface - the training seems to work but the infer breaks giving corrupted audio.

**Comment by Vidalnt** [comment]
> @blaise-tk to be honest, since BigGAN training is longer and more unstable, I couldn't get it converged on my gpu-poor setup :) code is adaptation of original implementation by nvidia + nsf filtering from original rvc

New: 
Anyway, it was my mistake as I had the inference, it seems that the model I am training seems to be on the right track.

> Old : 
> You are right about it being somewhat unstable, I was training and when I got past 25 epochs, the model started to do inference with statics.
> 
> Although it is possibly my mistake, I am training it from 0 again and with a 1 hour dataset.
